name: GitHub Teams Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 00:00 UTC

jobs:
  sync-teams:
    permissions:
      contents: read
    uses: actionsforge/actions/.github/workflows/gh-teams-sync.yml@main
    secrets:
      GH_ORG_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
